# Site settings
title: Fraser Reed
subtitle: Development.  Testing.  Frameworks.  Opinions.
email: contact@fraserreed.com
description: > # this means to ignore newlines until "baseurl:"
  Software development blog about servers, infrastructure, MVC frameworks, testing,
  performance, and best practices.  Software development is hard, it but doesn't have to be. Opinions are my own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.fraserreed.com"
twitter_username: fraser_reed
github_username:  fraserreed
linkedin_username: fraserreed

# Build settings
markdown: kramdown
